apiVersion: v1
kind: Service
metadata:
  name: ecm-sample-application-service
  labels:
    name: ecm-sample-application
    app: ecm-smart-service
spec:
  type: LoadBalancer
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    name: ecm-sample-application
    app: ecm-smart-service
